name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --all

  build:
    name: Build & release
    needs: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: x86_64-linux
            exe_suffix: ""

          - os: macos-latest
            target: x86_64-apple-darwin
            platform: x86_64-macos
            exe_suffix: ""

          - os: macos-latest
            target: aarch64-apple-darwin
            platform: aarch64-macos
            exe_suffix: ""

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: x86_64-windows
            exe_suffix: ".exe"

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename artifact
        shell: bash
        run: |
          VERSION="${GITHUB_REF_NAME}"
          BIN="alignomatic${{ matrix.exe_suffix }}"
          SRC="target/${{ matrix.target }}/release/$BIN"
          DST="alignomatic-$VERSION-${{ matrix.platform }}${{ matrix.exe_suffix }}"
          mv "$SRC" "$DST"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            alignomatic-${{ github.ref_name }}-${{ matrix.platform }}${{ matrix.exe_suffix }}

  checksums:
    name: Checksums
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download release assets
        uses: softprops/action-gh-release@v2
        with:
          download: true
          download_dir: assets

      - name: Generate SHA256SUMS
        run: |
          cd assets
          sha256sum alignomatic-* > SHA256SUMS.txt

      - name: Upload checksums
        uses: softprops/action-gh-release@v2
        with:
          files: assets/SHA256SUMS.txt
